### PR TITLE
Support go-relayer

### PR DESCRIPTION
**Pull request by Inkvi**
- Uses a polymer image for go-relayer
- There are no scripts to build a starship-compatible docker image for the relayer.

### CODE REVIEW

**Comment by Anmol1696** [comment]
This is really good. Could we add a test case for this in e2e tests.
https://github.com/cosmology-tech/starship/blob/main/tests/configs/two-chain.yaml

Basically we can just create the a new config file with go-relayer instead of Hermes (maybe `two-chain-gorelayer.yaml`?). We will run the tests accordingly anyways.

FYI: you would also need to add it to the github workflow here: https://github.com/cosmology-tech/starship/blob/main/.github/workflows/e2e-tests.yaml#L23 and and here: https://github.com/cosmology-tech/starship/blob/main/.github/workflows/pr-e2e-tests.yaml#L20

**Comment by Inkvi** [comment]
> This is really good. Could we add a test case for this in e2e tests. https://github.com/cosmology-tech/starship/blob/main/tests/configs/two-chain.yaml
> 
> Basically we can just create the a new config file with go-relayer instead of Hermes (maybe `two-chain-gorelayer.yaml`?). We will run the tests accordingly anyways.
> 
> FYI: you would also need to add it to the github workflow here: https://github.com/cosmology-tech/starship/blob/main/.github/workflows/e2e-tests.yaml#L23 and and here: https://github.com/cosmology-tech/starship/blob/main/.github/workflows/pr-e2e-tests.yaml#L20

I added a test case as you recommended. 

I tried running test cases locally but the cosmos hub validator fails on me and not all the tests pass. I doubt it's related to my changes but it's better to check for sure. Unfortunately, the github tests don't run for me. Is it something possible to allow me to do?

**Comment by Inkvi** [comment]
Nevermind, I think it was a fluke with. Now  I have no problems running tests locally.

**Comment by Inkvi** [comment]
One of the e2e tests fails for me locally. I can’t easily find out why.

```
=== RUN   TestE2ETestSuite/TestRegistry_ListIBC
    e2e_test.go:32: setting up e2e integration test suite...
    registry_test.go:121: running test for /ibc endpoint for registry
    registry_test.go:130: 
                Error Trace:    tests/registry_test.go:130
                Error:          "[]" should have 2 item(s), but has 0
                Test:           TestE2ETestSuite/TestRegistry_ListIBC
                Messages:       number of ibc information should be double the number of relayers
--- FAIL: TestE2ETestSuite (2.22s)
```

 @Anmol1696 Do you know what can be the reason? Does the relayer need to communicated with the registry?

**Comment by Anmol1696** [comment]
Ahh so by default for the relayers, we create the ibc-transfer ports between the two chains. The tests fails cuz it is expecting to have the channel created.

We can add the ibc-transfer creation to go-relayer for now, and then we can have a backlog task to basically make the ports creation on relayers to be a bit more explicit.

**Comment by Inkvi** [comment]
> Ahh so by default for the relayers, we create the ibc-transfer ports between the two chains. The tests fails cuz it is expecting to have the channel created.
> 
> We can add the ibc-transfer creation to go-relayer for now, and then we can have a backlog task to basically make the ports creation on relayers to be a bit more explicit.

Got it. I added the channel creation to `go-relayer`.

**Comment by Anmol1696** [comment]
@Inkvi this is awesome. Works like a charm.

We should figure out a way to be able to run e2e tests on a fork PR, but I ran the tests locally, and works.

**Pull request merged**
